version: '3.1'

services:
  app:
    container_name: spring-redis-exp
    build: ./
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - redis
    networks:
      - redis-exp
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-exp


networks:
  redis-exp:
    driver: bridge