pring:
  datasource:
    url: jdbc:h2:mem:denemeDB
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect


socket:
  host-name: 192.168.1.33
  port: 9090